#!/bin/bash

# Portable versions of the path functions (should work on Linux, MacOS and Windows)
function _dirname() { python -c 'import sys; from os.path import realpath, dirname; print(dirname(realpath(sys.argv[-1])))' $@ ; }
function _realpath() { python -c 'import sys; from os.path import realpath; print(realpath(sys.argv[-1]))' $@ ; }

export CUR_FILE=$(_realpath "$0")  # abs path of this script
export BIN_DIR=$(_dirname $CUR_FILE)  # abs path to the docker/help folder
export DOCKER_DIR=$(_dirname $BIN_DIR) # abs path to the docker folder

export TARGET_DIR="$DOCKER_DIR/config/httpd/ssl"

openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -out "$TARGET_DIR/localhost.pem" -keyout "$TARGET_DIR/localhost.key" -subj '/CN=localhost'