version: '3.7'

x-build-args: &build-args
  UID: ${USER_ID}

x-volumes: &volumes
  - ../..:/app'
  - '${APP_DIR}:${APP_DIR}'
  - '../config/httpd/sites-enabled:/etc/apache2/sites-enabled'
  - '../config/httpd/ports.conf:/etc/apache2/ports.conf'
  - '../config/php/php.ini:/usr/local/etc/php/php.ini'

x-debug-env-var: &x-debug-env-var 'remote_enable=1 remote_mode=req remote_port=${XDEBUG_PORT} remote_host=${XDEBUG_HOST} remote_connect_back=0'

x-environment: &environment
  APACHE_DOCUMENT_ROOT: ${APP_DIR}
  XDEBUG_CONFIG: *x-debug-env-var

services:
  # Apache
  apache:
    &apache
    build:
      context: ../service/php-7.1/apache
      target: apache
      args: *build-args
    network_mode: 'host'
    init: true
    restart: always
    volumes: *volumes
    environment: *environment
    depends_on:
      - mysql

  apache-xdebug:
    <<: *apache
    build:
      context: ../service/php-7.1/apache
      target: debug
      args: *build-args


  # PHP CLI
  php-cli:
    &php-cli
    build:
      context: ../service/php-7.1/cli
      target: cli
      args: *build-args
    network_mode: 'host'
    init: true
    restart: always
    volumes: *volumes
    environment: *environment

  php-cli-xdebug:
    <<: *php-cli
    build:
      context: ../service/php-7.1/cli
      target: debug
      args: *build-args


  # MySQL
  mysql:
    image: mysql:5.6
    env_file:
      - ../config/mysql/env
    restart: always
    network_mode: 'host'

  mysql-cli:
    image: mysql:5.6
    env_file:
      - ../config/mysql/env
      - ../../.env
    restart: always
    network_mode: 'host'
    command: 'bash -c "mysql -h 127.0.0.1 -uroot -D $$(echo $$SS_DATABASE_NAME | xargs)"'
