version: '2.4'


networks:
  behat:
    name: behat
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "behat"

    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24
          gateway: 192.168.4.1

  xdebug:
    name: xdebug
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "xdebug"

    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.1
