version: '2.4'

x-working-dir: &working-dir '/home/vagrant/bench'

# CLI
x-volumes: &volumes
  - "../../bench:/home/vagrant/bench"
  - "~/.bashrc:/home/vagrant/.bashrc"
  - "~/.bash_profile:/home/vagrant/.bash_profile"
  - "~/.gitconfig:/home/vagrant/.gitconfig"
  - "~/.cache/.composer/cache/:/home/vagrant/.composer/cache/"
  - "../configs/php/php.ini:/usr/local/etc/php/php.ini"
  - "../configs/php/session-memcached.ini:/usr/local/etc/php/conf.d/session-memcached.ini"


# CLI tests (with inactive xdebug)
x-volumes-t: &volumes-t
  - "../../bench:/home/vagrant/bench"
  - "~/.bashrc:/home/vagrant/.bashrc"
  - "~/.bash_profile:/home/vagrant/.bash_profile"
  - "~/.gitconfig:/home/vagrant/.gitconfig"
  - "~/.cache/.composer/cache/:/home/vagrant/.composer/cache/"
  - "../configs/php/php.ini:/usr/local/etc/php/php.ini"
  - "../configs/php/session-memcached.ini:/usr/local/etc/php/conf.d/session-memcached.ini"
  - "../configs/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"

# CLI debug (with active xdebug)
x-volumes-x: &volumes-x
  - "../../bench:/home/vagrant/bench"
  - "~/.bashrc:/home/vagrant/.bashrc"
  - "~/.bash_profile:/home/vagrant/.bash_profile"
  - "~/.gitconfig:/home/vagrant/.gitconfig"
  - "~/.cache/.composer/cache/:/home/vagrant/.composer/cache/"
  - "../configs/php/php.ini:/usr/local/etc/php/php.ini"
  - "../configs/php/session-memcached.ini:/usr/local/etc/php/conf.d/session-memcached.ini"
  - "../configs/php/xdebug-cli.ini:/usr/local/etc/php/conf.d/xdebug.ini"


# Apache
x-volumes-a: &volumes-a
  - "../../bench:/var/www/html"
  - "../configs/httpd/sites-enabled:/etc/apache2/sites-enabled"
  - "../configs/php/php.ini:/usr/local/etc/php/php.ini"
  - "../configs/php/session-memcached.ini:/usr/local/etc/php/conf.d/session-memcached.ini"

# Apache with xdebug
x-volumes-ax: &volumes-ax
  - "../../bench:/var/www/html"
  - "../configs/httpd/sites-enabled:/etc/apache2/sites-enabled"
  - "../configs/php/php.ini:/usr/local/etc/php/php.ini"
  - "../configs/php/session-memcached.ini:/usr/local/etc/php/conf.d/session-memcached.ini"
  - "../configs/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"


x-networks: &networks
  - default
  - xdebug
  - vagrant

x-extra-hosts: &extra-hosts
  - "vagrant:192.168.1.1"
  - "xdebug:192.168.3.1"
  - "chrome:192.168.1.1"


services:
  xdebug:
    build:
      context: ../service/xdebug_proxy
      args:
        HOST_OUT: xdebug
    init: true
    networks: *networks
    extra_hosts: *extra-hosts


  php56:
    build:
      context: ../service/php56/cli
      target: dev
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes
    working_dir: *working-dir


  php56cow:
    build:
      context: ../service/php56/cli
      target: cow
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes
    working_dir: *working-dir



  php56t:
    build:
      context: ../service/php56/cli
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes-t
    working_dir: *working-dir


  php56x:
    build:
      context: ../service/php56/cli
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes-x
    working_dir: *working-dir

  php56a:
    build:
      context: ../service/php56/apache
      target: base
    networks: *networks
    extra_hosts: *extra-hosts
    init: true
    restart: always
    ports:
      - "8560:80"
    volumes: *volumes-a

  php56ax:
    build:
      context: ../service/php56/apache
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    init: true
    restart: always
    ports:
      - "8561:80"
    volumes: *volumes-ax


  php70a:
    build:
      context: ../service/php70/apache
      target: base
    networks: *networks
    extra_hosts: *extra-hosts
    init: true
    restart: always
    ports:
      - "8700:80"
    volumes: *volumes-a

  php70ax:
    build:
      context: ../service/php70/apache
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    init: true
    restart: always
    ports:
      - "8701:80"
    volumes: *volumes-ax

  php70:
    build:
      context: ../service/php70/cli
      target: dev
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes
    working_dir: *working-dir

  php70t:
    build:
      context: ../service/php70/cli
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes-t
    working_dir: *working-dir

  php70cow:
    build:
      context: ../service/php70/cli
      target: cow
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes
    working_dir: *working-dir

  php70x:
    build:
      context: ../service/php70/cli
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes-x
    working_dir: *working-dir

  php71a:
    build:
      context: ../service/php71/apache
      target: base
    networks: *networks
    extra_hosts: *extra-hosts
    init: true
    restart: always
    ports:
      - "8710:80"
    volumes: *volumes-a

  php71ax:
    build:
      context: ../service/php71/apache
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    init: true
    restart: always
    ports:
      - "8711:80"
    volumes: *volumes-ax

  php71:
    build:
      context: ../service/php71/cli
      target: dev
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes
    working_dir: *working-dir

  php71t:
    build:
      context: ../service/php71/cli
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes-t
    working_dir: *working-dir

  php71cow:
    build:
      context: ../service/php71/cli
      target: cow
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes
    working_dir: *working-dir

  php71x:
    build:
      context: ../service/php71/cli
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes-x
    working_dir: *working-dir

  php72a:
    build:
      context: ../service/php72/apache
      target: base
    networks: *networks
    extra_hosts: *extra-hosts
    init: true
    restart: always
    ports:
      - "8720:80"
    volumes: *volumes-a

  php72ax:
    build:
      context: ../service/php72/apache
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    init: true
    restart: always
    ports:
      - "8721:80"
    volumes: *volumes-ax

  php72:
    build:
      context: ../service/php72/cli
      target: dev
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes
    working_dir: *working-dir

  php72t:
    build:
      context: ../service/php72/cli
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes-t
    working_dir: *working-dir

  php72cow:
    build:
      context: ../service/php72/cli
      target: cow
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes
    working_dir: *working-dir

  php72x:
    build:
      context: ../service/php72/cli
      target: debug
    networks: *networks
    extra_hosts: *extra-hosts
    volumes: *volumes-x
    working_dir: *working-dir
