version: '2.4'

services:
  chrome:
    network_mode: host
    image: selenoid/chrome
    restart: always
    init: true
    cap_add:
      - ALL

  # firefox:
  #   network_mode: host
  #   image: selenoid/firefox
  #   init: true
  #   cap_add:
  #     - ALL
