version: '2.4'

x-volumes: &volumes
  - "../../bench:/home/vagrant/bench"
  - "/home/vagrant/.cache/yarn:/home/node/.cache/yarn"
  - "/home/vagrant/.cache/.npm:/home/node/.cache/npm-cache"
  - "~/.bashrc:/home/node/.bashrc"
  - "~/.bash_profile:/home/node/.bash_profile"
  - "~/.gitconfig:/home/node/.gitconfig"

x-working-dir: &working-dir '/home/vagrant/bench'


services:
  node10:
    build:
      context: ../service/node10
      target: dev

    volumes: *volumes
    working_dir: *working-dir


  node6:
    build:
      context: ../service/node6
      target: dev

    volumes: *volumes
    working_dir: *working-dir
